dist: trusty
language: java
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"  
jdk:
  - oraclejdk8
sudo: required
install: true
before_script:
# for RCPTT tests
  - export SWT_GTK3=0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16"
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
script:
- mvn clean package -e -Dgpg.skip=true
- chmod a+x prepare-deploy-local-dir.sh
- export TAG_OR_BRANCH="${TRAVIS_BRANCH}/nightly"
- if [[ "$TRAVIS_TAG" != "" ]]; then export TAG_OR_BRANCH="${TRAVIS_TAG}"; fi
- "./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/${TAG_OR_BRANCH}"
after_script:
- chmod a+x travis-promote.sh
- ./travis-promote.sh
deploy:  
  - provider: s3
    access_key_id: AKIAI7GYGSUKTIBLAI6Q
    secret_access_key:
      secure: GE0B8oyxO6z3Z/sAmoHbo4oRjAZOEKQ0hwLagaPwYE+RPpOKZHYNeW7WNwTfxN2067Yic7VZpUPXLMNEs/xBlR7pnnZ+sfCQARGGlIPD9Dxaob6hX1jPJye60p217LR6sBX7q7swm0/XheSBU2EPHb1lBXn9Cw6fQtjZEWYBIWqrrJLB+OatOn7hZ119klhHJCbIz1i8QFmI65L+vXpwYDd6WlY6nT6tjxvyEUuRjQq8Yj3eiOm87vfwaoIHXsrylM4wg6BSGdX08WwIwuoIaSDjhAFKgjnFRIq7APufPWkrjEuggFAbha/GYGKAFq2DeA3E0hAnZSvjU3IeM/zaiYR3FH8wzYvsvhYMBGAE5ETD5aeQiKGU481n84x+WwNGvoNzdjWpKebYEb/thHBHHZJsopTf9z8eyrORgsxT2jJhJ5qHwab0bZy0R88mCR/MPchcX5GfzjkXGI0B1aDbjAYUNK91DFmlqAd75SLVGmUZG64RByOQlR291w+lVEoh0GkvKYAkX8swM5ZGMGJLW3MuzWodLOsGXhZwZHjzMT32kMMf+oi3nhFcyRRoG/6THaLdcoL+yXHCc4iU40wAI1TxJg511erh0MiwE5rJekjfdt/dZMvXQv0735n5GFIhRiE0S8aAkSoI1k3ajz/GtPFMFHHctOi6MOC+WAWdNLA=
    bucket: obeo-networkaggregation-releases
    local-dir: "${TRAVIS_BUILD_DIR}/${TAG_OR_BRANCH}"
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    upload-dir: capella-extensions/${TAG_OR_BRANCH}
    on:
      all_branches: true
      repo: ObeoNetwork/Capella-Extensions
