# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Environment
      run: |
        echo GITHUB_WORKSPACE $GITHUB_WORKSPACE
        echo GITHUB_REF $GITHUB_REF
        echo GITHUB_SHA $GITHUB_SHA
        echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
    - name: Set up JDK 1.8 and caches
    - uses: actions/checkout@v2
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      env:
        MAVEN_OPTS: -XX:MaxPermSize=512m -Xmx2048m -Xms1024m
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn clean verify -e -Dgpg.skip=true

    - name: Prepare deploy local directory
      env:
        TAG_OR_BRANCH: $(echo $GITHUB_REF | cut -d"/" -f3)/nightly
      run: |
        chmod a+x prepare-deploy-local-dir.sh
        if [[ "$(echo $GITHUB_REF | cut -d"/" -f2)" != "tags" ]]; then export TAG_OR_BRANCH="$(echo $GITHUB_REF | cut -d"/" -f3)"; fi
        ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/$TAG_OR_BRANCH

